modify

diff --git a/static/scripts/ora b/static/scripts/ora
--- a/static/scripts/ora
+++ b/static/scripts/ora
@@ -42,7 +42,6 @@
 # 2019-12-16 3.0   ==========================add sql check=========================
 # 2019-12-16 3.0.1 new command [batch_sqlhc]
 # 2019-12-16 2.0.3 add spool to log for most operation
-# 2019-12-15 2.0.2 new command [highcost];rename ash to ashcnt ;rename dash to dashcnt;rename ashtop/dashtop to ashsql/dashsql
 # 2019-12-14 2.0.1 adjust [sql] command ,add event info from gv_active_session_history; new command [dup_index]
 # 2019-12-09 2.0   =========================add -a -s -i option====================
 # 2019-12-08 1.3.0 add [table] an interactive mode : ora table <tab_name> [owner] ; add -e mode; rename index to [tabidx]; new commmand index ;
@@ -69,7 +68,6 @@
 # 2019-10-09 1.0.5 fix some display issue; new command  stat
 # 2019-10-04 1.0.4 new command  sparse_index , sparse_table , hintname; check command add foreign key no index
 # 2019-09-29 1.0.3 new command : load (awr load profile,in batch mode), top_seg (awr segment order by ,in batch mode)
-# 2019-09-26 1.0.2 fix some column format; change top command to topash; pc command order by ratio; sql command add more table info
 # 2019-09-22 1.0.1 new command :tbs_usage (fast but may not accurate), tbs_last (from snapshot,fast but may not accurate)
 # 2019-09-18 1.0.0 fix few bugs
 usage()
@@ -92,7 +90,7 @@ usage()
       - ashcnt [30]min                         active sessions count(gv_active_session_history),default recent 30min
       - ashdump  [1]min                        dump ash records into trc file,default value is 1 minutes
       - ashevent 10 2                          ora ashevent recent [10] minutes ,[def=2] ash top n events , grp by inst_id,sample_time,events
-      - ashsql \"14:15\" 20                      gv_active_session_history and dba_hist_active_sess_history ,group by sql_id and event
+      - snapper \"12:10\" 40                   AAS
       - ashtop | topash                        displays the latest time and the specified logical read SQL( default 10000)
       - asm                                    Show asm space/free space
       - awr [bid] [eid]                        ora awr bid eid (all nodes and RAC),top 50 sql;default is last 2 snapshots interval
@@ -118,7 +116,6 @@ usage()
 
       - dashcnt \"yyyy/mm/dd hh24:mi\" [30]    dba_hist_active_sess_history count by sample_time from given time last for 30(def) minutes
       - dashevent \"yyyy/mm/dd hh24:mi\" 20 2  ora dashevent given starttime,last for [20] min, top 2 events,grp by inst_id,sample_time,events
-      - dashsql                                same with ashsql
       - dblink/db_link/link                    show dblink Information
       - dbtime                                 dbtime by day / by top
       - ddl  <name> [owner] [type]             DDL info : dbms_metadata.get_ddl (Case Insensitive); all interactive mode
@@ -223,8 +220,6 @@ usage()
       - tbs                                    view all tablespace detail info
       - tbsinc                                 display total tablespace size by day
       - temp                                   view detail usage of temp tablespace
-      - topash [5]                             top sql/session/activity in recent n(def=5)minutes
-
       - toparea                                top sql in gv\$sqlarea : 5cpu/5reads/5elap
       - toparea_by_sig cpu|time|read <topn>    v#sqlarea group by force_matching_signature,topn
       - topsql_by_plan cpu|time|read <topn>    v#sql group by phv
@@ -2570,94 +2565,6 @@ ora histogram $2 $3 $4
 exit 0
 fi
 
-###################################################################################################################
-if [ "$1" = "ashsql" -o "$1" = "dashsql" ]; then
-
-   if [ "$2" = "" ]; then
-    defbtime=$(TZ=EST-7EDT date +"%H:%M")
-    defbtime2=$(TZ=EST-7EDT date +"%Y/%m/%d %H:%M")
-    #defbtime=`date +'%H:%M'`
-    read -p "Please input begin time,datetime format is [$defbtime](default) or [$defbtime2] :" btime
-      if [ -z "${btime}" ];then
-         btime=$defbtime
-         #echo "No input,exit"
-         #exit 1
-      fi
-    defdur=30
-    read -p "Please input duration time ,default is [$defdur]:" dur
-      if [ -z "${dur}" ];then
-         dur=$defdur
-      fi
-   else
-     btime=$2
-     dur=$3
-   fi
-
-    strlen=`echo $btime|wc -c|tr -d " "`
-    #echo $strlen
-    #exit
-
-   if [ $strlen -ne 6 -a $strlen -ne 17 ]; then
-       echo "date parameter format error. usage: ora ashsql 08:10 25 or ora ashsql \"2020/01/09 22:39\" 30 "
-       #echo "ora ashsql 08:10 25"
-       #echo "ora -i 1 ashsql \"2020/01/09 22:39\" 30"
-       exit 1
-   fi
-
-   #08:10  strlen=6
-   if [ $strlen = 6 ]; then
-      starttime="to_date(to_char(sysdate,'yyyy/mm/dd ')||'$btime','yyyy/mm/dd hh24:mi')"
-   fi
-
-   #2020/01/09 22:39 strlen=17
-   if [ $strlen = 17 ]; then
-      starttime="to_date('$btime','yyyy/mm/dd hh24:mi')"
-   fi
-   #echo $starttime
-
-  sqlplus -s /NOLOG << ! | egrep -v "Session altered|Connected|rows selected"
-
-    connect $DBUSER
-
-    set pagesize 30
-    set linesize 150
-    col sql_id format a15
-    col event format a40
-    set trimspool on
-    spool ora_ashsql_$filedate.log
-
-    Pro active_session_history   :
-     select * from
-    (select inst_id,sql_id,nvl(event,session_state) as event,count(*) as cnt from gv\$active_session_history
-    where sample_time between
-        $starttime
-    and $starttime+$dur/60/24
-    and inst_id=$INST and (sql_id is not null or event is not null)
-    group by inst_id,sql_id,nvl(event,session_state) having count(*)>=1
-    order by cnt desc
-    ) where rownum<=20;
-    $ECHO
-
-
-    Pro dba_hist_active_sess_history  :
-    select * from
-    (select instance_number as inst_id,sql_id,event,count(*) as cnt from dba_hist_active_sess_history
-    where sample_time between
-        $starttime
-    and $starttime+$dur/60/24
-    and instance_number=$INST and (sql_id is not null or event is not null)
-    group by instance_number,sql_id,event having count(*)>=1
-    order by cnt desc
-    ) where rownum<=20;
-    $ECHO
-    spool off
-!
-echo "instance_number=$INST"
-echo "ash and dash group by sql_id,evnet ,from $btime, last $dur ,top 20 sql with event"
-echo "ora ashsql <begin_time> <duration> [20]"
-exit 0
-fi
-
 ################################################################################
 if [ "$1" = "tbs_frag" ]; then
 
@@ -3215,6 +3122,49 @@ exit 0
 fi
 
 #########################################snapper_ash###################################################
+
+#   if [ "$2" = "" ]; then
+#    defbtime=$(TZ=EST-7EDT date +"%H:%M")
+#    defbtime2=$(TZ=EST-7EDT date +"%Y/%m/%d %H:%M")
+#    #defbtime=`date +'%H:%M'`
+#    read -p "Please input begin time,datetime format is [$defbtime](default) or [$defbtime2] :" btime
+#     if [ -z "${btime}" ];then
+#         btime=$defbtime
+#         #echo "No input,exit"
+#         #exit 1
+#      fi
+#    defdur=30
+#    read -p "Please input duration time ,default is [$defdur]:" dur
+#      if [ -z "${dur}" ];then
+#         dur=$defdur
+#      fi
+#   else
+#     btime=$2
+#     dur=$3
+#   fi
+
+#    strlen=`echo $btime|wc -c|tr -d " "`
+#    #echo $strlen
+#    #exit
+
+#   if [ $strlen -ne 6 -a $strlen -ne 17 ]; then
+#       echo "date parameter format error. usage: ora snapper 08:10 25 or ora snapper \"2020/01/09 22:39\" 30 "
+#       #echo "ora snapper 08:10 25"
+#       #echo "ora -i 1 snapper \"2020/01/09 22:39\" 30"
+#       exit 1
+#   fi
+
+#   #08:10  strlen=6
+#   if [ $strlen = 6 ]; then
+#      starttime="to_date(to_char(sysdate,'yyyy/mm/dd ')||'$btime','yyyy/mm/dd hh24:mi')"
+#   fi
+#
+#   #2020/01/09 22:39 strlen=17
+#  if [ $strlen = 17 ]; then
+#      starttime="to_date('$btime','yyyy/mm/dd hh24:mi')"
+#   fi
+#   #echo $starttime
+
 if [ "$1" = "snapper_ash" -o "$1" = "snapper" ]; then
 
  if [ "$2" = "" ]; then
@@ -5140,14 +5090,13 @@ col dbms_system_accessible clear
 
 set serveroutput off
 
---------------------------------------------------------------------------------
---     This script uses only the in-memory V$ACTIVE_SESSION_HISTORY, use
---     @dashtop.sql for accessiong the DBA_HIST_ACTIVE_SESS_HISTORY archive
---
---------------------------------------------------------------------------------
+
 prompt Start From $2 last $dur mintutes dba_hist_active_sess_history
 prompt ON CPU User I/O Network Commit Application Concurrency Cluster Configuration Administrative System I/O Scheduler Queueing Other Others for Wait_class%
 prompt ======================
+
+
+--    and instance_number=$INST
 
 set linesize 300 pages 50
 col MACHINE for a25
@@ -5264,6 +5213,9 @@ order by object_name, lock_mode_held desc
     $ECHO
     spool off
 !
+echo "instance_number=$INST"
+echo "ash and dash group by sql_id,evnet ,from $btime, last $dur ,top 20 sql with event"
+echo "ora ashsql <begin_time> <duration> [20]"
   exit 0
 fi
 ################################################################################
@@ -7254,8 +7206,6 @@ if [ "$1" = "kill" ]; then
   echo "alter system kill session '$2,$3,@$inst_id' immediate; command executed!"
 exit 0
 fi
-
-
 
 ################################################################################
 if [ "$1" = "topash" -o "$1" = "ashtop" -o "$1" = "top" ]; then
